import type { Metadata } from "next";
import "./globals.css";
import "./styles/themes.css";
import Header from './components/Header';
import Footer from './components/Footer/Footer';
import { CartProvider } from '@/app/providers/CartProvider';
import { RequestModalProvider } from './providers/RequestModalProvider';
import CartButton from '@/app/components/Cart/CartButton';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className="bg-white">
        <CartProvider>
          <RequestModalProvider>
            <Header />
            {children}
            <Footer />
            <CartButton />
          </RequestModalProvider>
        </CartProvider>
      </body>
    </html>
  );
}
